version: '2.1'

services:
  app:
    image: lunchkeeper-app
    container_name: lunchkeeper-app
    build: .
    depends_on:
      - api
  api:
    image: lunchkeeper-api
    container_name: lunchkeeper-api 
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
      ZOMATO_API_KEY: 7801edd0712e8d74b9947053e48a9f1a
    ports:
      - 3000:3000
      - 9229:9229
    depends_on: 
      - mongo
      - redis
    command: npm run start
  mongo:
    container_name: lunchkeeper-api-mongo
    image: mongo
    ports: 
      - "27017:27017"
  redis:
    container_name: lunchkeeper-api-redis
    image: redis
    ports: 
      - "6379:6379"
