version: '2.1'

services:
  lunchkeeper:
    image: lunchkeeper-api
    container_name: lunchkeeper-api 
    build: .
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    depends_on: 
      - mongo
      - redis
    command: npm run serve
    volumes:
      - .:/home/app/appDir
      - /home/app/appDir/node_modules
  mongo:
    container_name: lunchkeeper-api-mongo
    image: mongo
    ports: 
      - "27017:27017"
  redis:
    container_name: lunchkeeper-api-redis
    image: redis
    ports: 
      - "6379:6379"